### ISSUE TITLE
Add an option for only drop costs above a certain tonnage limit

### ISSUE THREAD

**Issue by Morphyum** [Morphyum/DropCostPerMech#2]

**Comment by ghost** [comment]
I wish I had some idea where you're pulling this magic reflection stuff from, wow.

I'll see if I can redo my changes, looks like the savestate is totally automated!!

**Comment by gnivler** [comment]
I'm going to give it a try, think I can manage.

**Comment by ghost** [comment]
Just about ready for a new PR (testing).  Delayed, (my) problems with saving.

Completed in #9

**Comment by daemonjax** [comment]
I just finished the code to do this for this myself... about to test it, and if it works, I'll put it here and on the nexus.

Yeah, works fine... here's my solution:  https://drive.google.com/open?id=1GG64WO8EDWVzNIOXx0NR4WPUYCBAseJ0

I didn't change much... just the Postfix function and added two settings.

**Comment by ghost** [comment]
I've had a complete PR open for a couple days now... code's been complete
for a while but the master branch was adjusted.

**Comment by Morphyum** [comment]
done in the newest patch, thanks gnivler
