### ISSUE TITLE
Post-mission drop cost always showing 0 cbills

### ISSUE THREAD

**Issue by ghost** [Morphyum/DropCostPerMech#6]
This appears to be happening with the master branch.

![image](https://user-images.githubusercontent.com/18452645/41186211-012cd692-6b50-11e8-8f52-93b9bc8dfde6.png)

Update
This mission showed it.  No bonuses, maybe that's related.

![image](https://user-images.githubusercontent.com/18452645/41186753-285da1fc-6b59-11e8-9a6d-f972c337c206.png)

I'm on friggin crack or something... whatever!  It went away magically.

![image](https://user-images.githubusercontent.com/18452645/41186781-df5b0188-6b59-11e8-9442-c91a9de3f352.png)

Further testing w/ my branch.

**Comment by ghost** [comment]
Not a bug

**Comment by Morphyum** [comment]
it is a bug i don't save the drop costs, so if you load into a mission after game restart it will show zero.

**Comment by ghost** [comment]
Cool.  My issue#2 branch is doing the same thing but otherwise working.

**Comment by Morphyum** [comment]
fixed in 1.0
